## 1.11 Homework 1: Introduction to Machine Learning

### Q1. Pandas version

What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [143]:
# Import Numpy, Pandas, matplotlib and seaborn libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [144]:
# Get version of Pandas

pd.__version__

'1.5.3'

### Getting the data

Source: Laptops Price dataset (https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv)

In [137]:
# Import dataset as Pandas dataframe 'laptops'

df_laptops = pd.read_csv('laptops.csv')

#### Q1 - Answer: 1.5.3

### Q2. Records count

How many records are in the dataset?

In [138]:
# Head and Shape of dataframe 'laptops'

laptops_head = df_laptops.head
laptops_shape = df_laptops.shape

print(laptops_head)
print(laptops_shape)

<bound method NDFrame.head of                                                  Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

         

#### Q2 - Answer: 2160

### Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [139]:
# Show all columns of dataframe 'laptops'

laptops_columns = df_laptops.columns

print(laptops_columns)

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')


In [140]:
# Show and count unique names in column 'Brand'

brands_unique = df_laptops['Brand'].unique()
brands_unique_num =  df_laptops['Brand'].nunique()

print(brands_unique)
print(brands_unique_num)

['Asus' 'Alurin' 'MSI' 'HP' 'Lenovo' 'Medion' 'Acer' 'Apple' 'Razer'
 'Gigabyte' 'Dell' 'LG' 'Samsung' 'PcCom' 'Microsoft' 'Primux' 'Prixton'
 'Dynabook Toshiba' 'Thomson' 'Denver' 'Deep Gaming' 'Vant' 'Innjoo'
 'Jetwing' 'Millenium' 'Realme' 'Toshiba']
27


#### Q3 - Answer: 27

### Q4. Missing values

How many columns in the dataset have missing values?

In [141]:
# Identify and count the number of columns with missing values in dataframe 'laptops'

laptops_col_null = df_laptops.isnull().any()
laptops_col_null_sum = df_laptops.isnull().sum().gt(0).sum()

print(laptops_col_null)
print(laptops_col_null_sum)

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool
3


#### Q4 - Answer: 3

### Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

In [142]:
# Filter dataframe 'laptops' by Brand 'Dell'

df_laptops_dell = df_laptops.loc[df_laptops['Brand']  == 'Dell']

df_laptops_dell_max_price = df_laptops_dell['Final Price'].max()

print(df_laptops_dell)
print(df_laptops_dell_max_price)

                                                 Laptop       Status Brand  \
161   Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...          New  Dell   
271   Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...          New  Dell   
281   Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...          New  Dell   
319   Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...          New  Dell   
328   Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...          New  Dell   
...                                                 ...          ...   ...   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
1844  Dell Vostro 5301 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1845  Dell Vostro 5502 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1846  Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512G...  Refurbished  Dell   
1847  Dell XPS 7390 Intel Core i7-10510U/16GB/512GB ...  Refurbished  Dell   

         Model            CPU  RAM  Storage Storage type  GPU  

#### Q5 - Answer: 3936

### Q6. Median value of Screen

1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method tofill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.

Has it changed?

Hint: refer to existing mode and median functions to complete the task.

In [90]:
# 1. Find the median value of Screen column in the dataset.

df_laptops_screen_median_before = df_laptops['Screen'].median()
print(df_laptops_screen_median_before)

15.6


##### Q6.1 - Answer: 15.6

In [93]:
# 2. Next, calculate the most frequent value of the same Screen column.

df_laptops_screen_mode = df_laptops['Screen'].mode()[0]
print(df_laptops_screen_mode)

15.6


##### Q6.2 - Answer: 15.6

In [99]:
# 3. Use fillna method tofill the missing values in Screen column with the most frequent value from the previous step.

df_laptops_screen_fill_mode = df_laptops['Screen'].fillna(df_laptops_screen_mode)

# Alternative, permanent change:
# df_laptops['Screen'] = df_laptops['Screen'].fillna(df_laptops_screen_mode, inplace = True)

In [100]:
# 4. Now, calculate the median value of Screen once again.

df_laptops_screen_median_after = df_laptops_screen_fill_mode.median()
print(df_laptops_screen_median_after)

# Alternative, permanent change:
# df_laptops_screen_median_after = df_laptops['Screen'].median()

15.6


##### Q6.4 - Answer: 15.6

#### Q6 - Answer: No

### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [107]:
# 1. Select all the "Innjoo" laptops from the dataset.

df_laptops_innjoo = df_laptops.loc[df_laptops['Brand'] == 'Innjoo']
print(df_laptops_innjoo)

                                                 Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128 

In [106]:
# 2. Select only columns RAM, Storage, Screen.

df_laptops_innjoo_sel_col = df_laptops_innjoo[['RAM', 'Storage', 'Screen']].values
print(df_laptops_innjoo_sel_col)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [108]:
# 3. Get the underlying NumPy array. Let's call it X.

X = df_laptops_innjoo_sel_col
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [119]:
#  4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T.
# Let's call the result XTX.

XTX = X.T @ X
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [120]:
# 5. Compute the inverse of XTX.

XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [123]:
# 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [125]:
# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = XTX_inverse @ X.T @ y

print(w)

[45.58076606  0.42783519 45.29127938]


In [145]:
# 8. What's the sum of all the elements of the result?

sum_w = np.sum(w).round(2)
print(sum_w)

91.3


#### Q7 - Answer: 91.30